### PR TITLE
chore(ci): Add initial ci for epython

### PR DESCRIPTION
**Pull request by xmnlab**
This PR aims to add an initial CI for epython.

PS: there is no issue opened for this, sorry if it is not pertinent. I'm totally fine with closing this or making any updates here as requested.

### CODE REVIEW

**Comment by xmnlab** [comment]
PS#2: I just saw some movements on epython and It motivated me to play with it a bit  :) sorry if this PR is not pertinent XD

**Comment by ilanschnell** [comment]
Looks good to me.

**Review by verhulstm — APPROVED** [review]
i like it

**Comment by anirrudh** [comment]
Hey @xmnlab, good to see you here! I like this too. Going to resolve the merge conflict, otherwise LGTM!

**Comment by anirrudh** [comment]
Merging, closing

**Pull request merged**
